routes/web.php
Route::group(['prefix' => 'admin',  'middleware' => 'prevent-back-history'], function()
{
     Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');

	Route::get('forgetpasword', 'Auth\AdminForgotPasswordController@showLinkRequestFormAdmin')->name('admin.forgetpassword');
    Route::post('password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');


	Route::post('password/reset', 'Auth\AdminResetPasswordController@reset')->name('admin.password.update');
    Route::get('password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    Route::post('/', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('dashboard', 'Admin\AdminController@index')->name('admin.home');
	Route::any('settings', 'Admin\AdminController@Settings')->name('admin.settings');
	Route::any('adminprofileupdate', 'Admin\AdminController@adminprofileupdate')->name('admin.adminprofileupdate');
	//Page Management
	Route::resource('page-management','Admin\PageController');
	Route::post('change_statuspage','Admin\PageController@ChangeStatusPage')->name('change_statuspage');

    //Banner Management
	Route::resource('promotional-banner-management','Admin\BannerController');
	Route::post('change_status2','Admin\BannerController@ChangeStatus')->name('change_statusbanner');

	//Subscription Management
	Route::resource('subscriiption-management','Admin\SubscriptionController');
	Route::post('change_status_subscription','Admin\SubscriptionController@ChangeStatus')->name('change_status_subscription');


	//Countyr Management
	Route::resource('country-management','Admin\CountryController');
	Route::post('change_statuscountr','Admin\CountryController@change_statuscountr')->name('change_statuscountr');

	//State Management
	Route::resource('state-management','Admin\StateController');
	Route::post('change_statusstate','Admin\StateController@Setstatus')->name('change_statusstate');

	//News/Reviews Management
	Route::resource('news-management','Admin\NewsController');
	Route::post('change_statusnews','Admin\NewsController@ChangeStatus')->name('change_statusnews');
	Route::resource('newsreview','Admin\NewsReviewController');
	Route::post('change_review','Admin\NewsReviewController@Setstatus')->name('setstatus');


   //Blog/Reviews Management
	Route::resource('blogs-management','Admin\BlogsController');
	Route::post('change_statusblog','Admin\BlogsController@ChangeStatus')->name('change_statusblog');
	Route::resource('blogreview','Admin\BlogsReviewController');
	Route::post('change_review_blog','Admin\BlogsReviewController@Setstatus')->name('change_review_blog');

	//Occasion/Reviews Management
	Route::resource('occasion-management','Admin\OccasionController');
	Route::post('change_statusoccasion','Admin\OccasionController@ChangeStatus')->name('change_statusoccasion');
	Route::resource('occasionreview','Admin\OccasionReviewController');
	Route::post('change_review_occasion','Admin\OccasionReviewController@Setstatus')->name('change_review_occasion');
	Route::post('get-areaadmin','Admin\OccasionController@GetArea')->name('get.areaadmin');


		//Testimonial Management
	Route::resource('testimonial-management','Admin\TestimonialController');
	Route::post('change_statustestimonial','Admin\TestimonialController@ChangeStatus')->name('change_statustestimonilal');

	//Notification Management
	Route::resource('notifcation-management','Admin\NotificaitonController');
	Route::post('change_statusnotification','Admin\NotificaitonController@ChangeStatus')->name('change_statusnotification');

	//Chat Management
	Route::resource('chat-management','Admin\ChatController');
	Route::post('change_statuschat','Admin\ChatController@ChangeStatus')->name('change_statuschat');

	//Promocode Management
	Route::resource('promocode-management','Admin\PromoCodeController');
	Route::post('change_statuspromo','Admin\PromoCodeController@ChangeStatus')->name('change_statuspromo');


	//Partner Event Management
	Route::resource('adminpartner-eventmangement','Admin\PartnerEventController');
	Route::any('manage-eventstatus', 'Admin\PartnerEventController@ChangeStatus')->name('manage-eventstatus');

	//Partner Rating Management
	Route::resource('adminpartner-ratingmangement','Admin\PartnerRatingController');
	Route::any('manage-ratingstatus', 'Admin\PartnerRatingController@ChangeStatus')->name('manage-ratingstatus');

    //Partner Event Booked Management
    Route::post('adminpartner-eventbookmangement','Admin\PartnerBookAvlController@index');
	Route::resource('adminpartner-eventbookmangement','Admin\PartnerBookAvlController',['except' => ['store']]);
    Route::any('manage-eventbookstatus', 'Admin\PartnerBookAvlController@ChangeStatus')->name('manage-eventbookstatus');



  //Booling Category Management
	Route::resource('category-management','Admin\CategoryController');
	Route::post('change_status','Admin\CategoryController@ChangeStatus')->name('change_statuscategory');

	//Sub Category Management
	Route::resource('subcategory-management','Admin\SubCategoryController');
	Route::post('change_statussubcategory','Admin\SubCategoryController@ChangeStatus')->name('change_statussubcategory');
	Route::post('change_statussubcategory2','Admin\SubCategoryController@ChangeStatus2')->name('change_statussubcategory2');

  //Sub Category Management
	Route::resource('tags-management','Admin\TagController');
	Route::post('change_statustags','Admin\TagController@ChangeStatus')->name('change_statustags');
	Route::post('change_statustags2','Admin\TagController@ChangeStatus2')->name('change_statustags2');

	//Organization Management
	Route::resource('organizaiton-management','Admin\OrganizatonController');
	Route::post('change_statusamenity','Admin\OrganizatonController@ChangeStatus')->name('change_statusamenity');

	//Booling Area Management
	Route::resource('area-management','Admin\AreaController');
	Route::post('change_statusarea','Admin\AreaController@ChangeStatus')->name('change_statusarea');
	Route::post('get-city','Admin\CityController@GetCity')->name('get.city');


	//City Room Category Management
	Route::resource('city-management','Admin\CityController');
	Route::post('setstatus-city', 'Admin\CityController@Setstatus')->name('setstatus_city');
	Route::post('setstatus-city3', 'Admin\CityController@Setstatus3')->name('setstatus_city3');
	Route::post('set_city_nav', 'Admin\CityController@set_city_nav')->name('set_city_nav');
	Route::post('get-country','Admin\CityController@GetCountry')->name('get.country');

	//Customer Management
	Route::resource('customer-management','Admin\AdminCustomerController');
	Route::post('change_statuscustomer','Admin\AdminCustomerController@ChangeStatusCustomer')->name('change_statuscustomer');
	Route::any('add-amount-customer/{id?}','Admin\AdminCustomerController@AddAmounttoCustoemr')->name('addamounttocustoemr');

	Route::resource('partner-management','Admin\PartnerController');
	Route::post('change_statuspartner','Admin\PartnerController@ChangeStatus')->name('change_statuspartner');
	Route::post('change_statuspartner2','Admin\PartnerController@ChangeStatus2')->name('change_statuspartner2');
    Route::post('add_amount','Admin\PartnerController@AddAmountPartner')->name('add_amount');
	Route::post('change_statuspartner_review','Admin\PartnerController@ChangeStatusReviws')->name('change_statuspartner_review');
	Route::post('get-location','Admin\AreaController@GetLocation')->name('get.location');
	Route::post('get-pincode','Admin\AreaController@GetPincode')->name('get.pincode');
	Route::post('get-publishedprice','Admin\HotelierController@GetPublishedprice')->name('get.publishedprice');

	Route::post("remove-image","Admin\HotelierController@removeImage")->name("remove.image");
	Route::post("thum-image","Admin\HotelierController@thumbImage")->name("thumb.image");

	Route::get('hotelier-management-registration', 'Admin\HotelierController@HotelierRegistration')->name('hotelier-management-registration');
	//Price setup
	Route::resource('room-details','Admin\RoomDetailController');
	Route::post('get-hotel-total-room','Admin\RoomDetailController@GetTotalRome')->name('get.Total.rooms');

	Route::resource('hotelier-slot','Admin\HotelierSlotController');
	Route::post('hotelier-slot-status','Admin\HotelierSlotController@Setstatus')->name('setstatus-slot');
    Route::post('get-roomdetails','Admin\HotelierSlotController@GetRoom')->name('get-roomdetails');

    // Wallet Transaction
    Route::post('wallet-transaction','Admin\WalletTransactionController@index');
    Route::resource('wallet-transaction','Admin\WalletTransactionController',['except' => ['store']]);

    // Purchased Subscription
    Route::post('purchased-subscription','Admin\PartnerSubscriptionController@index');
    Route::resource('purchased-subscription','Admin\PartnerSubscriptionController',['except' => ['store']]);

    //Advertisement Management
    Route::post('adminpartner-advertisement','Admin\PartnerAdvertisementController@index');
	Route::resource('adminpartner-advertisement','Admin\PartnerAdvertisementController',['except' => ['store']]);
    Route::any('manage-advertisementstatus', 'Admin\PartnerAdvertisementController@ChangeStatus')->name('manage-advertisementstatus');

    //Offer Management
    Route::post('offer-management','Admin\ManageOfferController@index');
	Route::resource('offer-management','Admin\ManageOfferController',['except' => ['store']]);
    Route::post('change_statusoffer','Admin\ManageOfferController@change_statusoffer')->name('change_statusoffer');


	//amdin logout
    Route::post('get-subcategory','Admin\PartnerController@Getsubcategory')->name('get-subcategory');
    Route::any('refered_employee', 'Admin\AdminController@referedEmployee')->name('admin.refered_employee');
    Route::any('getChatCount', 'Admin\AdminController@getChatCount')->name('admin.getChatCount');
    Route::get('logout', 'Auth\AdminLoginController@logout')->name('admin.logout');

app/PartnerAdvertisement.php
<?php
namespace App;
use Illuminate\Database\Eloquent\Model;
class PartnerAdvertisement extends Model
{
    protected $fillable = [];
	
	protected $appends = array('imagepath');
	public function getImagePathAttribute()
    {
        return asset('public/storage/upload/partneradvertisement/');
    }

	public function getPartner()
    {
    	return $this->belongsTo(Partner::class,'partner_id');
    }
	
}

app/Http/Controllers/Admin/PartnerAdvertisementController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\PartnerAdvertisement;
use Carbon\Carbon;
use Event;
use Illuminate\Support\Facades\DB;
class PartnerAdvertisementController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
	protected $perPage = 10;
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->partner_id){
            // echo "asdf";exit;
             $banners=PartnerAdvertisement::wherePartnerId($request->partner_id)->orderBy('id', 'desc')->get();
         }else{
            $banners= PartnerAdvertisement::orderBy('created_at', 'DESC')->get();
         }


    	return view("admin.partneradvertisement.list",compact('banners'));

      // echo "<a href='".route('admin.logout')."'>Logout</a>";
    }

	public function create()
    {


       return view("admin.partneradvertisement.add");
    }

	    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		$todate=date("Y-m-d",strtotime($request->todate));

		 $size="2048";
         $banner = new PartnerAdvertisement;
         $this->validate($request, [
            'name' => 'required',
            'image' => 'required|mimes:jpeg,jpg,png|max:'.$size.'',
            'description' => 'required',
			'position' => 'required',
         ]);

		if($request->hasfile('image'))
		 {
			  $file = $request->file('image');
			  $name=$this->timestamp_ms().'.'.$file->getClientOriginalExtension();
			  $destinationPath = public_path('storage/upload/partneradvertisement');
			  $file->move($destinationPath, $name);
		 }

		 $banner->name = $request->name;
		 $banner->status = 1;
		 $banner->description = $request->description;
		 $banner->position = $request->position;
		 $banner->todate  = $todate;
		 $banner->partner_id = $request->partner_id;
		 $banner->image = $name;
		 $banner->save();

		return redirect()->route('adminpartner-advertisement.index')->with(array(
            'success' => "Advertisement has been added"
        ));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function show(PartnerAdvertisement $banner)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function edit($banner)
    {
        $banner=PartnerAdvertisement::find($banner);

		return view('admin.partneradvertisement.edit',compact('banner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$banner)
    {
		$size="2048";

		$todate=date("Y-m-d",strtotime($request->todate));
        $banner=PartnerAdvertisement::find($banner);

		if($request->hasfile('image'))
		{
			$this->validate($request, [
            'image' => 'required|mimes:jpeg,jpg,png|max:'.$size.'',
			'position' => 'required',
         ]);

		}
		else
		{
			$this->validate($request, [
			'position' => 'required',
         ]);
		}
		if($request->hasfile('image'))
		 {
			if($banner ->image && file_exists(public_path('storage/upload/partneradvertisement').'/'.$banner ->image))
				unlink(public_path('storage/upload/partneradvertisement').'/'.$banner ->image);

			  $file = $request->file('image');
			  $name=$this->timestamp_ms().'.'.$file->getClientOriginalExtension();
			  $destinationPath = public_path('storage/upload/partneradvertisement');
			  $file->move($destinationPath, $name);
			  $banner->image = $name;
		 }

		 $banner->status = 1;
		 $banner->position = $request->position;
		 $banner->partner_id = $request->partner_id;
		 $banner->save();

     // return back()->with('success','Advertisement Updated');
      return redirect()->route('adminpartner-advertisement.index')->with(array(
        'success' => "Advertisement has been updated"
    ));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Banner  $banner
     * @return \Illuminate\Http\Response
     */
    public function destroy(PartnerAdvertisement $banner,$id)
    {
		$banner = PartnerAdvertisement::find($id);

		if($banner ->image)
			unlink(public_path('storage/upload/partneradvertisement').'/'.$banner ->image);

        $banner->delete();
		return back()->with('success','Advertisement Deleted');
    }

	public function timestamp_ms()
   {
    $time=round(microtime(true) * 1000);
    return $time;
  }

    public function ChangeStatus(Request $request){

    $id = $_POST['id'];
    $status = $_POST['status'];

	 if($status == '1'){
      $result = PartnerAdvertisement::where('id','=',$id)->update(['admin_status' => '0']);
    }else{
      $result = PartnerAdvertisement::where('id','=',$id)->update(['admin_status' => '1']);
    }

    echo $result;exit;
  }





}

resources/views/admin/partneradvertisement/add.blade.php
@extends('layouts.adminapp')
@section('titletag')
Partner Advertisement Management List : Add
@stop
@section('content')

          <!-- / .main-navbar -->
        
            <span class="clearfix"></span>
          <div class="main-content-container container-fluid px-4">
         
            <span class="clearfix"></span>
            <!-- Page Header -->
            <div class="page-header row no-gutters py-4">
              <div class="col-12 col-sm-5 text-center text-sm-left mb-0">
                <!-- <span class="text-uppercase page-subtitle">Overview</span> -->
                <h3 class="page-title">Partner Advertisement Management : Add</h3>
              </div>
            </div>
            <!-- End Page Header -->
            <!-- Default Light Table -->
            <div class="row">
              
              <div class="col-lg-12">
                <div class="card card-small mb-4 pt-3">
               <ul class="list-group list-group-flush">
                    <li class="list-group-item p-3">
                      <div class="row">
                        <div class="col">
                          {!! Form::open(['route'=>'adminpartner-advertisement.store','files'=>true]) !!}
						<div class="form-row">
                           
						   
						   @if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fa fa-check "></i>
          {{ $message }}</div>
@endif
                       
                            </div>
                            <div class="form-row">
	                                 <div class="form-group col-md-3">
                                <label for="#DDDDDD"> {!! Form::label('name','Advertisement Title *', []) !!}</label>
										{!! Form::text('name',null, ['class'=>'form-control','id'=>'name','placeholder'=>'Advertisement Title','required']) !!}
										
										 @if ($errors->has('name'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('name') }}</strong>
                        </span>
                     @endif
					 
								
                                 </div>
								 
								  <div class="form-group col-md-3">
                                 {!! Form::label('partner_id','Partner Name *', []) !!}

						{!! Form::select('partner_id',$partnerdetails,null, ['class'=>'form-control','required']) !!}
										
                      @if ($errors->has('partner_id'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('partner_id') }}</strong>
                        </span>
                     @endif
					 
					 
								
                                 </div>
								 
								 <div class="form-group col-md-3">
                                 {!! Form::label('position','Position *', []) !!}

                    {!! Form::select('position',$positiontype,null, ['class'=>'form-control','required']) !!}
                      @if ($errors->has('position'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('position') }}</strong>
                        </span>
                     @endif
					 
					 
								
                                 </div>
								 
								 <div class="form-group col-md-2">
                               <label for="#DDDDDD">  {!! Form::label('todate','Add End Date', []) !!}</label>
									  	
										{!! Form::text('todate',null, ['class'=>'form-control','id'=>'check_out_date','placeholder'=>'Add End Date','required']) !!}
										
										 @if ($errors->has('todate'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('todate') }}</strong>
                        </span>
                     @endif
                                 </div>
								 
								 
                              <div class="form-group col-md-3">
                                <label for="fePassword"> {!! Form::label('image','Image * (Image size <2MB )', []) !!}</label>
								 {!! Form::file('image', ['class'=>'form-control','id'=>'image','required']) !!}
								  @if ($errors->has('image'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('image') }}</strong>
                        </span>
                     @endif
                                 </div>
                            </div>
							
							
							
							<div class="form-row ">
							
							
			
							
							
							 <div class="form-group col-md-12">
                              <label for="feInputAddress">Description</label>
  
							  {!! Form::textarea('description',null, ['class'=>'form-control', 'maxlength'=>'50','id'=>'description','rows'=>'2','placeholder'=>'Description']) !!}
							  </div>

							 </div>
                           
                            <button type="submit" class="btn btn-accent">Submit</button>
							<button onclick="window.location.href='{{route('adminpartner-advertisement.index')}}';" type="button" class="btn btn-accent">Cancel</button>
                           {!! Form::close() !!}
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
                
              </div>
            </div>
            <!-- End Default Light Table -->
          </div>

@stop
@section('pagescript')
<script>

$(function() {
	
	 $( "#check_in_date" ).datepicker({ dateFormat: 'dd-mm-yy' }).val();
  $( "#check_out_date" ).datepicker({ dateFormat: 'dd-mm-yy' });
              // $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" }).val()
       });
</script>
@stop

resources/views/admin/partneradvertisement/edit.blade.php
@extends('layouts.adminapp')
@section('titletag')
Partner Advertisement Management : Edit
@stop
@section('content')

          <!-- / .main-navbar -->

            <span class="clearfix"></span>
          <div class="main-content-container container-fluid px-4">

            <span class="clearfix"></span>
            <!-- Page Header -->
            <div class="page-header row no-gutters py-4">
              <div class="col-12 col-sm-5 text-center text-sm-left mb-0">
                <!-- <span class="text-uppercase page-subtitle">Overview</span> -->
                <h3 class="page-title">Partner Advertisement Management : Edit</h3>
              </div>
            </div>
            <!-- End Page Header -->
            <!-- Default Light Table -->
            <div class="row">


              <div class="col-lg-12">
                <div class="card card-small mb-4 pt-3">
               <ul class="list-group list-group-flush">
                    <li class="list-group-item p-3">
                      <div class="row">
                        <div class="col">
                         {!! Form::model($banner, ["route"=>['adminpartner-advertisement.update',$banner->id],'files'=>true]) !!}

@method('PUT')
						<div class="form-row">




                            </div>
                            <div class="form-row">
								  <div class="form-group col-md-3">
                                 {!! Form::label('partner_id','Partner Name *', []) !!}

						{!! Form::select('partner_id',$partnerlist,null, ['class'=>'form-control','required']) !!}

                      @if ($errors->has('partner_id'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('partner_id') }}</strong>
                        </span>
                     @endif



                                 </div>

								  <div class="form-group col-md-3">
                                 {!! Form::label('position','Position *', []) !!}

                    {!! Form::select('position',$positiontype,null, ['class'=>'form-control','required']) !!}
                      @if ($errors->has('position'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('position') }}</strong>
                        </span>
                     @endif



                                 </div>




                              <div class="form-group col-md-3">
                                <label for="fePassword"> {!! Form::label('image','Image * (Image size <2MB )', []) !!}</label>
								@if($banner->image)
									{!! Form::file('image', ['class'=>'form-control','id'=>'image']) !!}
								@else
								 {!! Form::file('image', ['class'=>'form-control','id'=>'image','required']) !!}
							 @endif
								 <span><a href="{{asset('public/storage/upload/partneradvertisement/'.$banner->image.'')}}" target="_blank">{{$banner->image}}</a></span>
								  <br>@if ($errors->has('image'))
                        <span class="text-danger" role="alert">
                          <strong>{{ $errors->first('image') }}</strong>
                        </span>
                     @endif
                                 </div>
                            </div>

                            <button type="submit" class="btn btn-accent">Submit</button>
							<button onclick="window.location.href='{{route('adminpartner-advertisement.index')}}';" type="button" class="btn btn-accent">Cancel</button>
                           {!! Form::close() !!}
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>

              </div>
            </div>
            <!-- End Default Light Table -->
          </div>

@stop
@section('pagescript')
<script>

$(function() {

		 $( "#fromdate" ).datepicker({ dateFormat: 'dd-mm-yy',minDate: 0 });
  $( "#todate" ).datepicker({ dateFormat: 'dd-mm-yy',minDate: 0});
              // $("#datepicker").datepicker({ dateFormat: "yy-mm-dd" }).val()
       });

</script>
@stop

resources/views/admin/partneradvertisement/list.blade.php
@extends('layouts.adminapp')
@section('titletag')
Partner Advertisement Management List
@stop
@section('pagecss')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
@stop
@section('content')
          <!-- / .main-navbar -->

            <span class="clearfix"></span>
          <div class="main-content-container container-fluid px-4">

            <span class="clearfix"></span>
            <!-- Page Header -->
            <div class="page-header row no-gutters py-4">
              <div class="col-12 col-sm-5 text-center text-sm-left mb-0">
                <!-- <span class="text-uppercase page-subtitle">Overview</span> -->
                <h3 class="page-title">Partner Advertisement Management</h3>


              </div>
            </div>
            <!-- End Page Header -->
            <!-- Default Light Table -->
            <div class="row">

            @if ($message = Session::get('success'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fa fa-check "></i>
          {{ $message }}</div>
@endif

              <div class="col-lg-12">
                <div class="card card-small mb-4">
                  <div class="card-header border-bottom">

				   <!-- <button onclick="window.location.href='{{route('adminpartner-advertisement.create')}}';" class="btn btn-sm btn-accent ml-auto">
                          <i class="material-icons">file_copy</i> Add</button> -->

                          {!! Form::open(['route'=>'adminpartner-advertisement.index']) !!}

<div class="form-row">
    <div class="form-group col-md-4">
        <div class="styled-select">
            {!! Form::select('partner_id',$partnerlist,null, ['class'=>'form-control select2','placeholder'=>'Select Partner','required']) !!}
            @if ($errors->has('partner_id'))
                <span class="text-danger" role="alert">
                    <strong>{{ $errors->first('partner_id') }}</strong>
                </span>
            @endif
        </div>
    </div>
    <div class="form-group col-md-4">
        <button type="submit" class="btn btn-accent">Submit</button>
    </div>
</div>
{!! Form::close() !!}
                     <table class="table mb-0 table" id="example">
                      <thead class="bg-light">
                        <tr>
                          <th scope="col" class="border-0">Serial No</th>
						  <th scope="col" class="border-0">Position</th>
                          <th scope="col" class="border-0">Partner Name</th>
                          <th scope="col" class="border-0">Image</th>
                          <th scope="col" class="border-0">Status</th>
						  <th scope="col" class="border-0">Action</th>

                        </tr>
                      </thead>
					@php
					$count=0;
					@endphp
                      <tbody>

					   @foreach ($banners as $banner)
                       <tr>
                          <td>{{ ++$count }}</td>
                          <td>{{$banner->position}}</td>
                          <td>{{$banner->getPartner->company_name}}</td>
                          <td><a href="{{asset('public/storage/upload/partneradvertisement/'.$banner->image.'')}}" target="_blank"><img src="{{asset('public/storage/upload/partneradvertisement/'.$banner->image.'')}}" width="60" height="40"/></a></td>

						  <td> <a style="cursor: pointer;" onclick="changeStatus({{ $banner->id }},'{{ $banner->admin_status==0 ? "0" : "1"}}')">{{ $banner->admin_status==1 ? "Active" : "Inactive"}} </a> </td>


                         <td><a href="{{ route('adminpartner-advertisement.edit',$banner->id) }}">Edit</a> | <a href="javascript:void(0);" onclick="delete_field('delete-form{{ $banner->id }}')">Delete</a>
						 <form action="{{route('adminpartner-advertisement.destroy',[$banner->id])}}" method="POST" style="display: none;" id="delete-form{{ $banner->id }}">
				@method('DELETE')
				@csrf
				</form>

						 </td>
                        </tr>









						 @endforeach


                      </tbody>
                    </table>
                  </div>



                </div>
              </div>
            </div>
            <!-- End Default Light Table -->
          </div>

@stop
@section('pagescript')
<script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script>

	function delete_field(argument)
  {
    if(confirm("Are You Sure to Delete"))
    {
      $("#"+argument).submit();
    }
    else
    {
      return false;
    }
  }

	      function changeStatus(id,status){
        var url = "{{ url('')}}";
          $.ajax({
            type: "POST",
            url: '{{route("manage-advertisementstatus")}}',
            data:({
              id : id, _token: "{{csrf_token()}}",status: status
            }),
            cache: false,
            success: function(data){
             if(data==1){
                alert("Success! Status changed successfully");
                window.location.reload();
              }else{
                alert("Opps! Unable to change status.");
             }
            }
          });
      }


      $(document).ready(function() {
    $('#example').DataTable();
} );
    </script>
@stop