routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Route::group(['prefix' => 'admin',  'middleware' => 'prevent-back-history'], function()
{
     Route::get('/', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');

	Route::get('forgetpasword', 'Auth\AdminForgotPasswordController@showLinkRequestFormAdmin')->name('admin.forgetpassword');
    Route::post('password/email', 'Auth\AdminForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');


	Route::post('password/reset', 'Auth\AdminResetPasswordController@reset')->name('admin.password.update');
    Route::get('password/reset/{token}', 'Auth\AdminResetPasswordController@showResetForm')->name('admin.password.reset');

    Route::post('/', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('dashboard', 'Admin\AdminController@index')->name('admin.home');
	Route::any('settings', 'Admin\AdminController@Settings')->name('admin.settings');
	Route::any('adminprofileupdate', 'Admin\AdminController@adminprofileupdate')->name('admin.adminprofileupdate');
	//Page Management
	Route::resource('page-management','Admin\PageController');
	Route::post('change_statuspage','Admin\PageController@ChangeStatusPage')->name('change_statuspage');

    //Banner Management
	Route::resource('promotional-banner-management','Admin\BannerController');
	Route::post('change_status2','Admin\BannerController@ChangeStatus')->name('change_statusbanner');

	//Subscription Management
	Route::resource('subscriiption-management','Admin\SubscriptionController');
	Route::post('change_status_subscription','Admin\SubscriptionController@ChangeStatus')->name('change_status_subscription');


	//Countyr Management
	Route::resource('country-management','Admin\CountryController');
	Route::post('change_statuscountr','Admin\CountryController@change_statuscountr')->name('change_statuscountr');

	//State Management
	Route::resource('state-management','Admin\StateController');
	Route::post('change_statusstate','Admin\StateController@Setstatus')->name('change_statusstate');

	//News/Reviews Management
	Route::resource('news-management','Admin\NewsController');
	Route::post('change_statusnews','Admin\NewsController@ChangeStatus')->name('change_statusnews');
	Route::resource('newsreview','Admin\NewsReviewController');
	Route::post('change_review','Admin\NewsReviewController@Setstatus')->name('setstatus');


   //Blog/Reviews Management
	Route::resource('blogs-management','Admin\BlogsController');
	Route::post('change_statusblog','Admin\BlogsController@ChangeStatus')->name('change_statusblog');
	Route::resource('blogreview','Admin\BlogsReviewController');
	Route::post('change_review_blog','Admin\BlogsReviewController@Setstatus')->name('change_review_blog');

	//Occasion/Reviews Management
	Route::resource('occasion-management','Admin\OccasionController');
	Route::post('change_statusoccasion','Admin\OccasionController@ChangeStatus')->name('change_statusoccasion');
	Route::resource('occasionreview','Admin\OccasionReviewController');
	Route::post('change_review_occasion','Admin\OccasionReviewController@Setstatus')->name('change_review_occasion');
	Route::post('get-areaadmin','Admin\OccasionController@GetArea')->name('get.areaadmin');


		//Testimonial Management
	Route::resource('testimonial-management','Admin\TestimonialController');
	Route::post('change_statustestimonial','Admin\TestimonialController@ChangeStatus')->name('change_statustestimonilal');

	//Notification Management
	Route::resource('notifcation-management','Admin\NotificaitonController');
	Route::post('change_statusnotification','Admin\NotificaitonController@ChangeStatus')->name('change_statusnotification');

	//Chat Management
	Route::resource('chat-management','Admin\ChatController');
	Route::post('change_statuschat','Admin\ChatController@ChangeStatus')->name('change_statuschat');

	//Promocode Management
	Route::resource('promocode-management','Admin\PromoCodeController');
	Route::post('change_statuspromo','Admin\PromoCodeController@ChangeStatus')->name('change_statuspromo');


	//Partner Event Management
	Route::resource('adminpartner-eventmangement','Admin\PartnerEventController');
	Route::any('manage-eventstatus', 'Admin\PartnerEventController@ChangeStatus')->name('manage-eventstatus');

	//Partner Rating Management
	Route::resource('adminpartner-ratingmangement','Admin\PartnerRatingController');
	Route::any('manage-ratingstatus', 'Admin\PartnerRatingController@ChangeStatus')->name('manage-ratingstatus');

    //Partner Event Booked Management
    Route::post('adminpartner-eventbookmangement','Admin\PartnerBookAvlController@index');
	Route::resource('adminpartner-eventbookmangement','Admin\PartnerBookAvlController',['except' => ['store']]);
    Route::any('manage-eventbookstatus', 'Admin\PartnerBookAvlController@ChangeStatus')->name('manage-eventbookstatus');



  //Booling Category Management
	Route::resource('category-management','Admin\CategoryController');
	Route::post('change_status','Admin\CategoryController@ChangeStatus')->name('change_statuscategory');

	//Sub Category Management
	Route::resource('subcategory-management','Admin\SubCategoryController');
	Route::post('change_statussubcategory','Admin\SubCategoryController@ChangeStatus')->name('change_statussubcategory');
	Route::post('change_statussubcategory2','Admin\SubCategoryController@ChangeStatus2')->name('change_statussubcategory2');

  //Sub Category Management
	Route::resource('tags-management','Admin\TagController');
	Route::post('change_statustags','Admin\TagController@ChangeStatus')->name('change_statustags');
	Route::post('change_statustags2','Admin\TagController@ChangeStatus2')->name('change_statustags2');

	//Organization Management
	Route::resource('organizaiton-management','Admin\OrganizatonController');
	Route::post('change_statusamenity','Admin\OrganizatonController@ChangeStatus')->name('change_statusamenity');

	//Booling Area Management
	Route::resource('area-management','Admin\AreaController');
	Route::post('change_statusarea','Admin\AreaController@ChangeStatus')->name('change_statusarea');
	Route::post('get-city','Admin\CityController@GetCity')->name('get.city');


	//City Room Category Management
	Route::resource('city-management','Admin\CityController');
	Route::post('setstatus-city', 'Admin\CityController@Setstatus')->name('setstatus_city');
	Route::post('setstatus-city3', 'Admin\CityController@Setstatus3')->name('setstatus_city3');
	Route::post('set_city_nav', 'Admin\CityController@set_city_nav')->name('set_city_nav');
	Route::post('get-country','Admin\CityController@GetCountry')->name('get.country');

	//Customer Management
	Route::resource('customer-management','Admin\AdminCustomerController');
	Route::post('change_statuscustomer','Admin\AdminCustomerController@ChangeStatusCustomer')->name('change_statuscustomer');
	Route::any('add-amount-customer/{id?}','Admin\AdminCustomerController@AddAmounttoCustoemr')->name('addamounttocustoemr');

	Route::resource('partner-management','Admin\PartnerController');
	Route::post('change_statuspartner','Admin\PartnerController@ChangeStatus')->name('change_statuspartner');
	Route::post('change_statuspartner2','Admin\PartnerController@ChangeStatus2')->name('change_statuspartner2');
    Route::post('add_amount','Admin\PartnerController@AddAmountPartner')->name('add_amount');
	Route::post('change_statuspartner_review','Admin\PartnerController@ChangeStatusReviws')->name('change_statuspartner_review');
	Route::post('get-location','Admin\AreaController@GetLocation')->name('get.location');
	Route::post('get-pincode','Admin\AreaController@GetPincode')->name('get.pincode');
	Route::post('get-publishedprice','Admin\HotelierController@GetPublishedprice')->name('get.publishedprice');

	Route::post("remove-image","Admin\HotelierController@removeImage")->name("remove.image");
	Route::post("thum-image","Admin\HotelierController@thumbImage")->name("thumb.image");

	Route::get('hotelier-management-registration', 'Admin\HotelierController@HotelierRegistration')->name('hotelier-management-registration');
	//Price setup
	Route::resource('room-details','Admin\RoomDetailController');
	Route::post('get-hotel-total-room','Admin\RoomDetailController@GetTotalRome')->name('get.Total.rooms');

	Route::resource('hotelier-slot','Admin\HotelierSlotController');
	Route::post('hotelier-slot-status','Admin\HotelierSlotController@Setstatus')->name('setstatus-slot');
    Route::post('get-roomdetails','Admin\HotelierSlotController@GetRoom')->name('get-roomdetails');

    // Wallet Transaction
    Route::post('wallet-transaction','Admin\WalletTransactionController@index');
    Route::resource('wallet-transaction','Admin\WalletTransactionController',['except' => ['store']]);

    // Purchased Subscription
    Route::post('purchased-subscription','Admin\PartnerSubscriptionController@index');
    Route::resource('purchased-subscription','Admin\PartnerSubscriptionController',['except' => ['store']]);

    //Advertisement Management
    Route::post('adminpartner-advertisement','Admin\PartnerAdvertisementController@index');
	Route::resource('adminpartner-advertisement','Admin\PartnerAdvertisementController',['except' => ['store']]);
    Route::any('manage-advertisementstatus', 'Admin\PartnerAdvertisementController@ChangeStatus')->name('manage-advertisementstatus');

    //Offer Management
    Route::post('offer-management','Admin\ManageOfferController@index');
	Route::resource('offer-management','Admin\ManageOfferController',['except' => ['store']]);

resources/views/admin/inc/commonscript.blade.php
<script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" ></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>

    <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>

    <script src="{{ asset('public/assets/admin/scripts/extras.1.0.0.min.js')}}"></script>

    <script src="{{ asset('public/assets/admin/scripts/sweetalert.min.js')}}"></script>

    <script src="{{ asset('public/assets/admin/scripts/shards-dashboards.1.0.0.min.js')}}"></script>

    <script src="{{ asset('public/assets/admin/scripts/app/app-blog-overview.1.0.0.js')}}"></script>

    <script src="https://use.fontawesome.com/b4b0414965.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

<script type="text/javascript">
     $('.select2').select2();
</script>
    <script>

      $(document).ready(function() {

  $(".nav a").click(function() {

    var link = $(this);

    var closest_ul = link.closest("ul");

    var parallel_active_links = closest_ul.find(".active");

    var closest_li = link.closest("li");

    var link_status = closest_li.hasClass("active");

    var count = 0;



    closest_ul.find("ul").slideUp("fast", function() {

      if (++count == closest_ul.find("ul").length)

        parallel_active_links.removeClass("active");

    });



    if (!link_status) {

      closest_li.children("ul").slideDown("fast");

      closest_li.addClass("active");

    }

  });


    setInterval(function () {
        var url = "{{ url('')}}";
          $.ajax({
            type: "POST",
            url: '{{route("admin.getChatCount")}}',
            data:({
               _token: "{{csrf_token()}}"
            }),
            cache: false,
            success: function(data){

                    $("#badge_count").html(data);
            }
        });
    },3000);

});



    </script>

resources/views/admin/inc/footer.blade.php
<footer class="main-footer bg-white border-top text-center" style="line-height: 4;">

          Copyright © {{\Carbon\Carbon::now()->year}} Phone2bazaar. <!--<span class="social"><a class="fa fa-facebook"></a> <a class="fa fa-twitter"></a> <a class="fa fa-linkedin"></a>
            <a class="fa fa-instagram"></a></span>-->
          </footer>

resources/views/admin/inc/nav-top.blade.php
		  <div class="main-navbar sticky-top bg-white">
            <!-- Main Navbar -->
            <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">

              <div style="cursor:pointer;" onclick="window.location.href='{{route('admin.home')}}';" class="input-group input-group-seamless ml-3">
                <img id="main-logo" class="d-inline-block align-top mr-1" src="{{ asset('public/assets/admin/img/logo.png')}}" alt="Highway">

                  </div>
                  <ul class="navbar-nav border-left flex-row ">
               <li class="nav-item border-right dropdown notifications">
                 <a class="nav-link nav-link-icon text-center" href="{{route('customer-management.index')}}" id="dropdownMenuLink">
                   <div class="nav-link-icon__wrapper">
                     <i class="material-icons">&#xE7F4;</i>
                     <span class="badge badge-pill badge-danger" id="badge_count"></span>
                   </div>
                 </a>

               </li>
              <li class="nav-item">
                          <a class="nav-link  text-nowrap px-3">

                          <span class="d-none d-md-inline-block">{{auth()->guard('admin')->user()->name}}</span>
                          </a>

                       </li>
             </ul>
              <nav class="nav">
                <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                  <i class="material-icons">&#xE5D2;</i>
                </a>
              </nav>
            </nav>
          </div>

resources/views/admin/inc/nav.blade.php
 <aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">

	<div class="nav-wrapper nav">
		<ul class=" flex-column nav__list" style="padding: 0; float: left; width: 100%;">
			<li class="nav-item">
				<a class="nav-link active" href="{{route('admin.home')}}">
					<i class="material-icons">home</i>
					<span>Dashboard</span>
				</a>
			</li>
            <li class="nav-item">
				<a href="#" class="nav-link"><i class="material-icons">view_module </i>
					<span>Category Management <em class="fa fa-angle-right"></em></span> </a>
				<ul class="group-list">
					<li><a href="{{route('category-management.index')}}">Category List</a></li>
					<li><a href="{{route('subcategory-management.index')}}">Sub Category</a></li>

				</ul>
			</li>

            <li class="nav-item">
				<a href="{{route('subscriiption-management.index')}}" class="nav-link"><i class="material-icons">power_settings_new </i>
					<span>Subscription Management</span>
				</a>
			</li>
            <li class="nav-item">
				<a href="#" class="nav-link"><i class="material-icons">view_module </i>
					<span>State Management <em class="fa fa-angle-right"></em></span> </a>
				<ul class="group-list">
					<li><a href="{{route('state-management.index')}}">State List</a></li>
					<li><a href="{{route('city-management.index')}}">City List</a></li>

				</ul>
			</li>

            	<li class="nav-item">
				<a href="#" class="nav-link"><i class="material-icons">view_module </i>
					<span>Partner Management <em class="fa fa-angle-right"></em></span> </a>
				<ul class="group-list">
					<li><a href="{{route('partner-management.index')}}">Partner List</a></li>
					<li><a href="{{route('wallet-transaction.index')}}">Partner Wallet Transaction</a></li>
					<li><a href="{{route('purchased-subscription.index')}}">Partner Subscription</a></li>
					<li><a href="{{route('adminpartner-advertisement.index')}}">Partner Advertisement</a></li>
                    <li><a href="{{route('offer-management.index')}}">Partner Offers</a></li>
                    <li><a href="{{route('adminpartner-eventbookmangement.index')}}">Partner Booked Availability</a></li>
					<!--<li><a href="{{route('hotelier-management-registration')}}">Register as Hotelier</a></li>
					<!{1}**<li><a href="{{route('room-details.index')}}">Hotel Price List</a></li>**{1}> -->
				</ul>
			</li>
            <li class="nav-item">
				<a href="#" class="nav-link"><i class="material-icons">view_module </i>
					<span>Customer Management <em class="fa fa-angle-right"></em></span> </a>
				<ul class="group-list">
					<li><a href="{{route('customer-management.index')}}">Customer List</a></li>
				</ul>
			</li>
            <li class="nav-item">
				<a href="{{route('admin.refered_employee')}}" class="nav-link"><i class="material-icons">power_settings_new </i>
					<span>Reffered Employee</span>
				</a>
			</li>
            <li class="nav-item">
				<a href="#" class="nav-link"><i class="material-icons">note_add</i>
					<span>Page Management <em class="fa fa-angle-right"></em></span> </a>
				<ul class="group-list">
					<li><a href="{{route('page-management.index')}}">Page List</a></li>
				</ul>
			</li>
            <li class="nav-item">
				<a href="{{route('admin.logout')}}" class="nav-link"><i class="material-icons">power_settings_new </i>
					<span>Logout</span>
				</a>
			</li>

		</ul>
	</div>
</aside>